halflife.wad
de_piranesi.wad
cs_assault.wad
cs_bdog.wad
cstrike.wad
itsitaly.wad
torntextures.wad
cs_havana.wad
chateau.wad
gfx/env/city1up.tga
gfx/env/city1dn.tga
gfx/env/city1lf.tga
gfx/env/city1rt.tga
gfx/env/city1ft.tga
gfx/env/city1bk.tga
sound/scientist/scream1.wav
models/hostage.mdl
models/scientist.mdl
sound/ambience/computalk2.wav
sound/ambience/disgusting.wav
sound/ambience/the_horror1.wav
sound/ambience/the_horror2.wav
sound/ambience/the_horror3.wav
sound/ambience/the_horror4.wav
sound/ambience/rocket_groan3.wav
sound/ambience/rocket_groan2.wav
sound/ambience/rocket_groan1.wav
sprites/flare1.spr
models/can.mdl
sprites/xsmoke1.spr
models/gman.mdl
sound/buttons/latchlocked1.wav
