maps/de_dust2_xmas.txt
maps/de_dust2_xmas.res
gfx/env/arcnbk.tga
gfx/env/arcndn.tga
gfx/env/arcnft.tga
gfx/env/arcnlf.tga
gfx/env/arcnrt.tga
gfx/env/arcnup.tga
overviews/de_dust2_xmas.txt
overviews/de_dust2_xmas.bmp
models/xmasblock/lekstok.mdl
models/xmasblock/sneeuwman.mdl
models/xmasblock/snow_tree.mdl
models/xmasblock/traineau_2.mdl
sound/xmasblock/coolwind2.wav
