gfx/env/dustup.tga
gfx/env/dustrt.tga
gfx/env/dustdn.tga
gfx/env/dustlf.tga
gfx/env/dustbk.tga
gfx/env/dustft.tga
maps/de_tuscan.txt
maps/de_tuscan.res
overviews/de_tuscan.txt
overviews/de_tuscan.bmp
