cs_bdog.wad
de_vegas.wad
gfx/env/backalleybk.tga
gfx/env/backalleydn.tga
gfx/env/backalleyft.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyup.tga
halflife.wad
models/gman.mdl
models/lv_bottle.mdl
models/uplant1.mdl
overviews/de_vegas_32.bmp
overviews/de_vegas_32.txt
sound/ambience/lv1.wav
sound/ambience/lv2.wav
sound/ambience/lv3.wav
sound/ambience/lv4.wav
sound/ambience/lv5.wav
sound/ambience/lv6.wav